sablier-labs/lockup

- package.json
Closes #372.
I'll ship `@sablier/v2-core@1.0.0-rc.0` to the npm registry (with a `rc` tag, not `latest`) after we merge this PR.
> build: change version to 1.0.0-rc.0

- script/DeployDeterministicComptroller.s.sol
- script/DeployDeterministicCore.s.sol
- script/DeployDeterministicLockupDynamic.s.sol
- script/DeployDeterministicLockupLinear.s.sol
- script/DeployDeterministicNFTDescriptor.s.sol
Using strings for the `create2Salt` parameter allows us to use the version as a CREATE2 salt, e.g.
- `1.0.0-rc.0`
- `Comptroller v1.0.0-rc.0`
- `SablierV2Comptroller v1.0.0-rc.0`
> refactor: stringify create2 salts

- script/Base.s.sol
- script/DeployComptroller.s.sol
- script/DeployCore.s.sol
- script/DeployDeterministicComptroller.s.sol
- script/DeployDeterministicCore.s.sol
- script/DeployDeterministicLockupDynamic.s.sol
- script/DeployDeterministicLockupLinear.s.sol
- script/DeployDeterministicNFTDescriptor.s.sol
- script/DeployLockupDynamic.s.sol
- script/DeployLockupLinear.s.sol
- script/DeployNFTDescriptor.s.sol
- script/Init.s.sol
- test/utils/Utils.sol
This PR does two things:
- Rename `deployer` to `broadcaster` in `BaseScript` (not all scripts deploy contracts)
- Allows the user to pass the broadcaster key and address via the command line (e.g. by passing `--ledger` and setting the `ETH_FROM` environment variable)
I needed to make this refactor to be able to deploy using Ledger.
> refactor: rename deployer to broadcaster

- package.json
- pnpm-lock.yaml
- src/types/Math.sol
- src/types/Tokens.sol
`solhint-community` can now be used in V2 Core - they've fixed all false positives:
https://github.com/solhint-community/solhint-community/pull/21
> chore: use solhint-community

- test/integration/concrete/comptroller/set-flash-fee/setFlashFee.t.sol
Base on the pattern, the `test_SetFlashFee` test seems to be missing the defined modifier to describe that this is in the "is admin x whenNewFee" branch
> chore: add missing modifier in test_SetFlashFee

- src/SablierV2LockupDynamic.sol
- src/SablierV2LockupLinear.sol
- src/abstracts/SablierV2Lockup.sol
Closes https://github.com/sablier-labs/v2-core/issues/610
> perf: dry "isCold" and "isWarm"

- test/integration/concrete/lockup-dynamic/streamed-amount-of/streamedAmountOf.t.sol
- test/integration/concrete/lockup-dynamic/streamed-amount-of/streamedAmountOf.tree
- test/integration/concrete/lockup-dynamic/withdrawable-amount-of/withdrawableAmountOf.t.sol
- test/integration/concrete/lockup-dynamic/withdrawable-amount-of/withdrawableAmountOf.tree
- test/integration/concrete/lockup-linear/streamed-amount-of/streamedAmountOf.tree
- test/integration/concrete/lockup-linear/withdrawable-amount-of/withdrawableAmountOf.t.sol
- test/integration/concrete/lockup-linear/withdrawable-amount-of/withdrawableAmountOf.tree
- test/integration/concrete/lockup/status-of/statusOf.t.sol
- test/integration/concrete/lockup/status-of/statusOf.tree
- test/integration/concrete/lockup/withdraw-max/withdrawMax.t.sol
- test/integration/concrete/lockup/withdraw-max/withdrawMax.tree
- test/integration/concrete/lockup/withdraw/withdraw.t.sol
- test/integration/concrete/lockup/withdraw/withdraw.tree
- test/integration/fuzz/lockup/withdrawMax.t.sol
- test/integration/shared/lockup/withdrawMax.t.sol
Reference: https://github.com/sablier-labs/v2-periphery/pull/178#issuecomment-1705151676
> test: use "given" instead of "when"

- .solhint.json
- src/abstracts/NoDelegateCall.sol
- test/fork/Fork.t.sol
- test/fork/LockupDynamic.t.sol
- test/fork/LockupLinear.t.sol
- test/fork/assets/DAI.t.sol
- test/fork/assets/EURS.t.sol
- test/fork/assets/SHIB.t.sol
- test/fork/assets/USDC.t.sol
- test/fork/assets/USDT.t.sol
Closes https://github.com/sablier-labs/v2-core/issues/699
Note: being a small change I think this shouldn't be included in the `CHANGELOG` .
> refactor: capitalize immutable variables 

- foundry.toml
The CBOR metadata can be enabled as it won't affect deterministic compilation across operating systems.
Ref https://twitter.com/msolomon44/status/1659301831489757187
> chore: remove "cbor_metadata"

- .github/workflows/ci.yml
- slither.config.json
Addresses https://github.com/sablier-labs/v2-core/issues/418.
Recreated from https://github.com/sablier-labs/v2-core/pull/431.
> ci: add slither job

- .github/workflows/deploy-comptroller.yml
- .github/workflows/deploy-core.yml
- .github/workflows/deploy-lockup-dynamic.yml
- .github/workflows/deploy-lockup-linear.yml
- .github/workflows/deploy-nft-descriptor.yml
- SECURITY.md
- foundry.toml
Remove goerli support in `foundry.toml` file and use sepolia as default chain in deployment workflows.
> build: remove goerli support

- script/DeployDeterministicCore.s.sol
- script/DeployDeterministicCore2.s.sol
- script/DeployDeterministicLockupDynamic.s.sol
- script/DeployDeterministicLockupLinear.s.sol
- script/DeployLockupDynamic.s.sol
- test/integration/concrete/nft-descriptor/safe-asset-symbol/safeAssetSymbol.t.sol
Foundry changed something in their latest release and the formatting is now different.
> chore: fix forge formatting

- shell/deploy-multi-chain.sh
> Use array to create deployment command

- shell/deploy-multi-chain.sh
Fixes https://github.com/sablier-labs/v2-core/pull/753#issuecomment-1867729757
> chore: create an array for deployment command

- package.json
To prevent accidental cases whereby the node modules are not updated when the package is published to the npm registry.
> build: install deps in prepack

- .github/workflows/ci-deep.yml
- .github/workflows/ci-slither.yml
- .github/workflows/ci.yml
- .github/workflows/stale.yml
This PR reduces the complexity of our CI workflows by de-duplicating as much logic as possible. Most of the jobs in the CI workflows are now reusable, and they can be imported from this repository:
https://github.com/sablier-labs/reusable-workflows
Please look at the README of that repository for more details on what workflows are available.
> ci: use reusable workflows

- foundry.toml
- script/Base.s.sol
- script/DeployDeterministicComptroller.s.sol
- script/DeployDeterministicCore.s.sol
- script/DeployDeterministicCore2.s.sol
- script/DeployDeterministicCore3.s.sol
- script/DeployDeterministicLockupDynamic.s.sol
- script/DeployDeterministicLockupLinear.s.sol
- script/DeployDeterministicNFTDescriptor.s.sol
- shell/deploy-multi-chain.sh
- test/utils/BaseScript.t.sol
Addresses https://github.com/sablier-labs/v2-core/discussions/810
I decided to log the string salt to visually see what is being passed (also testing it, in case something is not working).
@smol-ninja, can you check, please, if I missed anything in the multi-chain script?
> feat: add a util function to construct the create2 salt

- src/SablierV2NFTDescriptor.sol
- test/mocks/NFTDescriptorMock.sol
- test/unit/concrete/nft-descriptor/generateDescription.t.sol
Closes https://github.com/sablier-labs/v2-core/issues/818
> refactor: change disclaimer when the nft is non-transferable

- .github/workflows/ci-fork.yml
- .github/workflows/ci.yml
Closes https://github.com/sablier-labs/v2-core/issues/790
I have decided to run the tests once every two days.
Sunday is not included because on that day, they already run in the `ci-deep` workflow.
https://github.com/sablier-labs/v2-core/blob/9ebb59abfdbe3eb1f286ed4e04c849bad51e7113/.github/workflows/ci-deep.yml#L68-L77
> ci: run fork tests only monday, wednesday and friday

- src/abstracts/SablierV2Lockup.sol
- test/integration/concrete/lockup-dynamic/LockupDynamic.t.sol
- test/integration/concrete/lockup-linear/LockupLinear.t.sol
- test/integration/concrete/lockup/withdraw-hooks/withdrawHooks.t.sol
- test/integration/concrete/lockup/withdraw-hooks/withdrawHooks.tree
- test/integration/concrete/lockup/withdraw/withdraw.t.sol
- test/integration/shared/lockup-dynamic/LockupDynamic.t.sol
- test/integration/shared/lockup-linear/LockupLinear.t.sol
- test/integration/shared/lockup/Lockup.t.sol
- test/integration/shared/lockup/withdraw.t.sol
> fix: avoid duplicate calls on withdraw hook when sender is also the recipient

- .github/workflows/ci-fork.yml
- .github/workflows/ci.yml
Closes https://github.com/sablier-labs/v2-core/issues/832.
I have moved precompile tests alongside fork tests which run periodically on Monday, Wednesday and Friday. Should I rename `ci-fork` file to encapsulate both fork and precompile tests?
> Schedule precompile tests to mon, wed and fri

- codecov.yml
- package.json
- precompiles/Precompiles.sol
- shell/update-precompiles.sh
- test/utils/Precompiles.t.sol
> Move precompiles to precompiles directory

- test/integration/concrete/lockup/withdraw-hooks/withdrawHooks.t.sol
- test/integration/concrete/lockup/withdraw-hooks/withdrawHooks.tree
- test/integration/concrete/lockup/withdraw/withdraw.t.sol
- test/integration/shared/lockup-dynamic/LockupDynamic.t.sol
- test/integration/shared/lockup-linear/LockupLinear.t.sol
- test/integration/shared/lockup-tranched/LockupTranched.t.sol
- test/integration/shared/lockup/Lockup.t.sol
- test/integration/shared/lockup/withdraw.t.sol
- test/utils/Assertions.sol
- As identified by @PaulRBerg in https://github.com/sablier-labs/v2-core/pull/826#issuecomment-2027572212, this PR brings back the tests for withdraw hooks
- Adds `solhint-disable event-name-camelcase` rule in Assertions
> test: integration tests for withdraw hooks

- script/Base.s.sol
- script/DeployCore.s.sol
- script/DeployCore2.s.sol
- script/DeployDeterministicCore.s.sol
- script/DeployDeterministicCore2.s.sol
- script/DeployDeterministicLockupDynamic.s.sol
- script/DeployDeterministicLockupTranched.s.sol
- script/DeployLockupDynamic.s.sol
- script/DeployLockupTranched.s.sol
Since `maxSegmentCount` and `maxTrancheCount` have still been used in forge scripts, the contracts would be deployed with 0 value for `MAX_SEGEMENT_COUNT` and `MAX_TRANCHE_COUNT`.
> fix: use `segmentCountMap` and `trancheCountMap` in forge scripts

- test/integration/concrete/lockup-dynamic/create-with-durations/createWithDurations.t.sol
- test/integration/concrete/lockup-dynamic/create-with-durations/createWithDurations.tree
- test/integration/concrete/lockup-tranched/create-with-durations/createWithDurations.t.sol
- test/integration/concrete/lockup-tranched/create-with-durations/createWithDurations.tree
- test/integration/fuzz/lockup-dynamic/createWithDurations.t.sol
- test/integration/fuzz/lockup-dynamic/createWithTimestamps.t.sol
- test/integration/fuzz/lockup-tranched/createWithDurations.t.sol
- test/integration/shared/lockup/createWithDurations.t.sol
- Closes https://github.com/sablier-labs/v2-core/issues/956
- Replaced `test_RevertWhen_LoopCalculationOverflowsBlockGasLimit` with `test_RevertWhen_SegmentCountTooHigh` since the function reverts if the count exceeds the max count defined in the contract. https://github.com/sablier-labs/v2-core/blob/3ee63dbeb570b133eb4095e211a5e736704c144c/src/libraries/Helpers.sol#L138
So we may not need the loop test anymore.
> test: keep gas usage below foundry 1B limit

- .github/workflows/ci-deep.yml
Closes https://github.com/sablier-labs/v2-core/issues/965.
This fixes the issue as can be seen in [this manual run](https://github.com/sablier-labs/v2-core/actions/runs/9828167040). Solution found in [this discussion](https://github.com/actions/runner/issues/2206#issuecomment-1532246677).
> ci: use `fromJSON` to convert string into digits

- src/interfaces/ISablierV2Lockup.sol
- src/interfaces/ISablierV2LockupDynamic.sol
- src/interfaces/ISablierV2LockupTranched.sol
Let's put constants at the top from here on out.
> refactor: reorder constant functions in interface

- benchmark/BatchLockup.Gas.t.sol
- benchmark/Benchmark.t.sol
- benchmark/LockupDynamic.Gas.t.sol
- benchmark/LockupLinear.Gas.t.sol
- benchmark/LockupTranched.Gas.t.sol
- benchmark/results/SablierV2BatchLockup.md
- benchmark/results/SablierV2LockupDynamic.md
- benchmark/results/SablierV2LockupLinear.md
- benchmark/results/SablierV2LockupTranched.md
- shell/deploy-multi-chain.sh
- shell/prepare-artifacts.sh
Please refer to https://github.com/sablier-labs/v2-core/pull/979 notes.
- add [batch lockup benchmark contract](https://github.com/sablier-labs/v2-periphery/blob/main/benchmark/BatchLockup.Gas.t.sol)
- dry-fy params return in core benchmarks
- run benchmarks to update results
> Add periphery benchmark

- .github/workflows/ci-deep.yml
- .github/workflows/ci-fork.yml
- .github/workflows/ci.yml
- .github/workflows/generate-svg.yml
- benchmark/BatchLockup.Gas.t.sol
- benchmark/Benchmark.t.sol
- benchmark/LockupDynamic.Gas.t.sol
- benchmark/LockupLinear.Gas.t.sol
- benchmark/LockupTranched.Gas.t.sol
- benchmark/results/SablierV2BatchLockup.md
- benchmark/results/SablierV2LockupDynamic.md
- benchmark/results/SablierV2LockupLinear.md
- benchmark/results/SablierV2LockupTranched.md
- shell/deploy-multi-chain.sh
- shell/prepare-artifacts.sh
Please refer to https://github.com/sablier-labs/v2-core/pull/979 notes.
- run the tests for both core and periphery in CI
- lower the number of fuzz runs for integration tests
- the reason for this is because it takes a long time to pass (more tests added) the CI, and the operation would be canceled by github.
> Include both core and periphery tests in CI

- script/periphery/CreateMerkleLL.s.sol
- script/periphery/CreateMerkleLT.s.sol
- src/periphery/SablierMerkleFactory.sol
- src/periphery/SablierMerkleLL.sol
- src/periphery/SablierMerkleLT.sol
- src/periphery/interfaces/ISablierMerkleFactory.sol
- src/periphery/interfaces/ISablierMerkleLL.sol
- src/periphery/interfaces/ISablierMerkleLT.sol
- src/periphery/types/DataTypes.sol
- test/periphery/Periphery.t.sol
- test/periphery/fork/merkle-campaign/MerkleLL.t.sol
- test/periphery/fork/merkle-campaign/MerkleLT.t.sol
- test/periphery/integration/merkle-campaign/MerkleCampaign.t.sol
- test/periphery/integration/merkle-campaign/factory/create-merkle-ll/createMerkleLL.t.sol
- test/periphery/integration/merkle-campaign/factory/create-merkle-lt/createMerkleLT.t.sol
- test/periphery/integration/merkle-campaign/ll/claim/claim.t.sol
- test/periphery/integration/merkle-campaign/ll/claim/claim.tree
- test/periphery/integration/merkle-campaign/ll/constructor.t.sol
- test/periphery/integration/merkle-campaign/lt/claim/claim.t.sol
- test/periphery/integration/merkle-campaign/lt/claim/claim.tree
- test/periphery/integration/merkle-campaign/lt/constructor.t.sol
- test/utils/Defaults.sol
- test/utils/Events.sol
Closes #996 
Some problems in the issue:
- In `MerkleLL` the case when cliff duration is 0 was not covered
- In `MerkleLT`the `startTime + MerkleLT.TrancheWithPercentage.duration // recursively` was not correct, but only for the first tranche
> feat: use `createWithTimestamps` in `claim`

- .github/workflows/ci-deep.yml
- .github/workflows/ci-fork.yml
Closes [this Notion task](https://www.notion.so/sablier/Set-up-notifications-for-failed-CI-runs-96249855570245e4bf746b58c7ab3f4c).
Using https://github.com/marketplace/actions/slack-notify to send a notification to the `#ci-notifications` channel on Slack whenever there's a failure in the scheduled workflow CI Deep.
@smol-ninja should this also be added to the fork tests workflow, as well as the `staging` branch?
> ci: slack notify integration

- README.md
Description:
link to LICENSE-GPL is updated now because it was invalid.
No test needed
> docs: fix link to LICENSE-GPL

- .github/workflows/ci-deep.yml
- .github/workflows/ci-fork.yml
The [most recent CI Deep run](https://github.com/sablier-labs/v2-core/actions/runs/11310928833) failed, but the `#ci-notifications` Slack channel didn't get notified.
Hopefully, this PR will fix it.
> ci: fix slack notify

- .gitignore
- foundry.toml
- tests/fork/LockupDynamic.t.sol
- tests/fork/LockupTranched.t.sol
- tests/integration/concrete/lockup-dynamic/create-with-timestamps-ld/createWithTimestampsLD.t.sol
- tests/integration/concrete/lockup-dynamic/get-segments/getSegments.t.sol
- tests/integration/concrete/lockup-tranched/create-with-durations-lt/createWithDurationsLT.t.sol
- tests/integration/concrete/lockup-tranched/create-with-timestamps-lt/createWithTimestampsLT.t.sol
- tests/integration/concrete/lockup-tranched/get-tranches/getTranches.t.sol
- tests/integration/fuzz/lockup-dynamic/createWithDurationsLD.t.sol
- tests/integration/fuzz/lockup-dynamic/createWithTimestampsLD.t.sol
- tests/integration/fuzz/lockup-tranched/createWithDurationsLT.t.sol
- tests/integration/fuzz/lockup-tranched/createWithTimestampsLT.t.sol
- tests/utils/Assertions.sol
In this PR https://github.com/sablier-labs/v2-core/pull/1089/ the `script/protocol` dir was removed without updating the `fs_permissions` in `foundry.toml` and the `.gitignore` file.
Also, found out, we don't need all the assert functions declared in `Assertions`.
The `assertEq` functions for segments are already emitting the fact that we compare an array of segments/tranches.
Depends on: #1094 and #1095
> Small fixes and polishes

- src/LockupNFTDescriptor.sol
- src/abstracts/SablierLockupBase.sol
- src/interfaces/ISablierLockupBase.sol
- tests/fork/LockupDynamic.t.sol
- tests/fork/LockupLinear.t.sol
- tests/fork/LockupTranched.t.sol
- tests/integration/concrete/lockup-base/getters/getters.t.sol
- tests/integration/concrete/lockup-base/getters/getters.tree
- tests/integration/concrete/lockup-dynamic/create-with-durations-ld/createWithDurationsLD.t.sol
- tests/integration/concrete/lockup-dynamic/create-with-timestamps-ld/createWithTimestampsLD.t.sol
- tests/integration/concrete/lockup-linear/create-with-durations-ll/createWithDurationsLL.t.sol
- tests/integration/concrete/lockup-linear/create-with-timestamps-ll/createWithTimestampsLL.t.sol
- tests/integration/concrete/lockup-tranched/create-with-durations-lt/createWithDurationsLT.t.sol
- tests/integration/concrete/lockup-tranched/create-with-timestamps-lt/createWithTimestampsLT.t.sol
- tests/integration/fuzz/lockup-dynamic/createWithDurationsLD.t.sol
- tests/integration/fuzz/lockup-dynamic/createWithTimestampsLD.t.sol
- tests/integration/fuzz/lockup-linear/createWithDurationsLL.t.sol
- tests/integration/fuzz/lockup-linear/createWithTimestampsLL.t.sol
- tests/integration/fuzz/lockup-tranched/createWithDurationsLT.t.sol
- tests/integration/fuzz/lockup-tranched/createWithTimestampsLT.t.sol
In https://github.com/sablier-labs/v2-core/pull/1097, @andreivladbrg renamed `getAsset` to `getToken`.
`getToken` can be easily confused with the ERC-721 NFT functions.
It'd be better to rename it to `getUnderlyingToken`.
> refactor: get underlying token

- .solhint.json
- src/abstracts/SablierLockupBase.sol
- src/interfaces/ISablierLockupBase.sol
- tests/integration/concrete/lockup-base/withdraw-multiple/withdrawMultiple.t.sol
- tests/integration/concrete/lockup-base/withdraw-multiple/withdrawMultiple.tree
- tests/utils/Modifiers.sol
Closes https://github.com/sablier-labs/v2-core/issues/917
> feat: use delegate-call in withdraw-multiple

- foundry.toml
- package.json
- tests/utils/BaseScript.t.sol
The size of the `SablierLockup` contract passes the limit:
```
| SablierLockup                 |           25,069 |            26,085 |               -493 |              23,067 |
```
So we need to lower the optimizer runs to 800.
Also, update the package json version to `2.0.0`
> build: lower optimizer runs

- tests/integration/concrete/lockup-base/collect-fees/collectFees.t.sol
- tests/integration/concrete/lockup-base/collect-fees/collectFees.tree
- tests/utils/Modifiers.sol
As pointed out here: https://github.com/sablier-labs/flow/pull/348#discussion_r1885084440
> test: update branch

- benchmark/LockupDynamic.Gas.t.sol
- benchmark/LockupLinear.Gas.t.sol
- benchmark/LockupTranched.Gas.t.sol
- benchmark/results/SablierLockup_Dynamic.md
- benchmark/results/SablierLockup_Linear.md
- benchmark/results/SablierLockup_Tranched.md
- src/LockupNFTDescriptor.sol
- src/SablierLockup.sol
- src/interfaces/ISablierLockup.sol
- src/interfaces/ISablierLockupBase.sol
- src/libraries/VestingMath.sol
- refactor: add blockTimestamp param in VestingMath functions
- refactor: remove unchecked in calculateStreamedPercentage
- docs: add assumptions in VestingMath function
- docs: improve explanatory comments
Addresses these audit findings:
- https://cantina.xyz/code/52d6aa1e-6aa4-4e73-96ed-6077652cf0f1/findings/3
- https://cantina.xyz/code/52d6aa1e-6aa4-4e73-96ed-6077652cf0f1/findings/5
- https://cantina.xyz/code/52d6aa1e-6aa4-4e73-96ed-6077652cf0f1/findings/11
> Address audit findings 3, 5, and 11

- tests/integration/Integration.t.sol
- tests/integration/concrete/batch/batch.t.sol
- tests/integration/concrete/lockup-base/allow-to-hook/allowToHook.t.sol
- tests/integration/concrete/lockup-base/cancel/cancel.t.sol
- tests/integration/concrete/lockup-base/getters/getters.t.sol
- tests/integration/concrete/lockup-base/withdraw-hooks/withdrawHooks.t.sol
- tests/integration/concrete/lockup-base/withdraw/withdraw.t.sol
- tests/integration/fuzz/lockup-base/cancel.t.sol
Closes https://github.com/sablier-labs/v2-core/issues/1129
> test: move all `allowedToHook` calls in Integration contract

- script/Init.s.sol
- shell/prepare-artifacts.sh
- src/SablierLockup.sol
- src/interfaces/ISablierBatchLockup.sol
- src/interfaces/ISablierLockup.sol
- src/libraries/Helpers.sol
- src/libraries/StreamingMath.sol
- src/types/DataTypes.sol
- tests/fork/LockupDynamic.t.sol
- tests/fork/LockupLinear.t.sol
- tests/fork/LockupTranched.t.sol
- tests/integration/concrete/lockup-linear/streamed-amount-of/streamedAmountOf.t.sol
- tests/integration/fuzz/lockup-dynamic/createWithDurationsLD.t.sol
- tests/integration/fuzz/lockup-dynamic/createWithTimestampsLD.t.sol
- tests/integration/fuzz/lockup-dynamic/streamedAmountOf.t.sol
- tests/integration/fuzz/lockup-dynamic/withdrawableAmountOf.t.sol
- tests/integration/fuzz/lockup-linear/streamedAmountOf.t.sol
- tests/integration/fuzz/lockup-linear/withdrawableAmountOf.t.sol
- tests/integration/fuzz/lockup-tranched/createWithDurationsLT.t.sol
- tests/integration/fuzz/lockup-tranched/createWithTimestampsLT.t.sol
- tests/integration/fuzz/lockup-tranched/streamedAmountOf.t.sol
- tests/integration/fuzz/lockup-tranched/withdrawableAmountOf.t.sol
- tests/invariant/Invariant.t.sol
- tests/utils/Calculations.sol
- tests/utils/DeployOptimized.t.sol
Closes https://github.com/sablier-labs/lockup/issues/1134
> docs: renaming of functions and variables

- .solhint.json
- src/libraries/StreamingMath.sol
- tests/fork/Fork.t.sol
- tests/fork/Lockup.t.sol
- tests/fork/LockupDynamic.t.sol
- tests/fork/LockupLinear.t.sol
- tests/fork/LockupTranched.t.sol
- tests/integration/concrete/lockup-base/getters/getters.t.sol
- tests/integration/concrete/lockup-dynamic/create-with-durations-ld/createWithDurationsLD.t.sol
- tests/integration/concrete/lockup-dynamic/create-with-timestamps-ld/createWithTimestampsLD.t.sol
- tests/integration/concrete/lockup-linear/create-with-durations-ll/createWithDurationsLL.t.sol
- tests/integration/concrete/lockup-linear/create-with-timestamps-ll/createWithTimestampsLL.t.sol
- tests/integration/concrete/lockup-linear/get-unlock-amounts/getUnlockAmounts.t.sol
- tests/integration/concrete/lockup-tranched/create-with-durations-lt/createWithDurationsLT.t.sol
- tests/integration/concrete/lockup-tranched/create-with-timestamps-lt/createWithTimestampsLT.t.sol
- tests/integration/fuzz/lockup-dynamic/createWithDurationsLD.t.sol
- tests/integration/fuzz/lockup-dynamic/createWithTimestampsLD.t.sol
- tests/integration/fuzz/lockup-linear/createWithDurationsLL.t.sol
- tests/integration/fuzz/lockup-linear/createWithTimestampsLL.t.sol
- tests/integration/fuzz/lockup-tranched/createWithDurationsLT.t.sol
- tests/integration/fuzz/lockup-tranched/createWithTimestampsLT.t.sol
- tests/utils/Assertions.sol
- tests/utils/Calculations.sol
- tests/utils/Defaults.sol
- tests/utils/EstimateMaxCount.sol
Closes https://github.com/sablier-labs/lockup/issues/1127
- Adds a new `Lockup.t.sol` abstract contract in `tests/fork` directory.
- DRY'ifies fork tests by moving common code into the new `Lockup.t.sol` abstract contract.
- Adds string `err` in `assertEq` of `Lockup.Model` for consistency in `tests/utils/Assertions.sol`
- Adds `assertEq` to compare `SablierLockupBase` states in `tests/utils/Assertions.sol`
- Fixes some streamed amount calculations in `tests/utils/Calculations.sol`
- Adds 2 new functions in `tests/utils/Defaults.sol`
- Fix `tests/utils/EstimateMaxCount.sol` to not fail in case of default profile
> test: refactor fork tests to use a shared contract

- tests/fork/Fork.t.sol
We should run fork tests only on the latest block. Since Ethereum global state is irreversible, fork tests will always pass at a specified block if it has been passing before. 
Running tests on the latest block would imply that the tests are passing on the most recent state of the Sablier protocol.
Merging this change through a PR so that we can verify that the fork tests are passing.
> ci: run fork tests on latest block

- .gitignore
- README.md
- remappings.txt
Closes https://github.com/sablier-labs/lockup/issues/1237 
**Note:** I didn't remove the section about `remappings` in the case of `forge install`, as it would still be required when using git submodules.
> Remove remappings

- LICENSE-BUSL.md
- LICENSE.md
- bun.lock
- package.json
- src/SablierLockup.sol
- src/interfaces/ISablierLockup.sol
- tests/integration/concrete/constructor.t.sol
- tests/integration/concrete/lockup/allow-to-hook/allowToHook.t.sol
- tests/integration/concrete/lockup/recover/recover.t.sol
- tests/integration/concrete/lockup/set-native-token/setNativeToken.t.sol
- tests/integration/concrete/lockup/set-nft-descriptor/setNFTDescriptor.t.sol
- tests/invariant/README.md
Refer to https://github.com/sablier-labs/evm-utils/pull/43
> refactor: ComptrollerManager to Comptrollerable

- bun.lock
- package.json
- src/SablierLockup.sol
- src/interfaces/ISablierLockup.sol
- tests/integration/concrete/lockup/calculate-min-fee-wei-for/calculateMinFeeWeiFor.t.sol
- tests/integration/concrete/lockup/calculate-min-fee-wei-for/calculateMinFeeWeiFor.tree
Refer to https://github.com/sablier-labs/evm-utils/pull/44.
Depends on https://github.com/sablier-labs/lockup/pull/1268.
The new function `calculateMinFeeWei` is added to Lockup contract because it would be useful for external contracts to query fee for a given stream ID from the Lockup contract itself and then use the returned value in the withdraw function. Without the function, they will have to query it from comptroller using stream's sender and then use that value in withdraw function - a poor UX.
> feat: function to calculate min fee in wei for a given stream ID
