test/integration/basic/lockup-linear/create-with-range/createWithRange.tree
test/integration/fuzz/lockup-linear/createWithRange.t.sol

Addresses @IaroslavMazur's finding.

test: remove duplicate bounds

---

README.md

Add Contribution info in README.md

---

test/utils/Utils.sol

test: change default profile value

---

test/integration/concrete/lockup-dynamic/streamed-amount-of/streamedAmountOf.t.sol
test/integration/concrete/lockup-dynamic/streamed-amount-of/streamedAmountOf.tree
test/integration/concrete/lockup-dynamic/withdrawable-amount-of/withdrawableAmountOf.t.sol
test/integration/concrete/lockup/burn/burn.t.sol
test/integration/concrete/lockup/cancel-multiple/cancelMultiple.t.sol
test/integration/concrete/lockup/cancel-multiple/cancelMultiple.tree
test/integration/concrete/lockup/cancel/cancel.t.sol
test/integration/concrete/lockup/cancel/cancel.tree
test/integration/concrete/lockup/is-depleted/isDepleted.t.sol
test/integration/concrete/lockup/is-depleted/isDepleted.tree
test/integration/concrete/lockup/renounce/renounce.t.sol
test/integration/concrete/lockup/renounce/renounce.tree
test/integration/concrete/lockup/status-of/statusOf.t.sol
test/integration/concrete/lockup/withdraw/withdraw.t.sol
test/integration/concrete/lockup/withdraw/withdraw.tree
test/integration/concrete/nft-descriptor/map-symbol/mapSymbol.tree
test/integration/concrete/nft-descriptor/safe-asset-decimals/safeAssetDecimals.tree
test/integration/concrete/nft-descriptor/safe-asset-symbol/safeAssetSymbol.t.sol
test/integration/concrete/nft-descriptor/safe-asset-symbol/safeAssetSymbol.tree
test/integration/fuzz/lockup-dynamic/streamedAmountOf.t.sol
test/integration/fuzz/lockup-dynamic/withdrawableAmountOf.t.sol
test/integration/fuzz/lockup/cancel.t.sol
test/integration/fuzz/lockup/cancelMultiple.t.sol
test/integration/shared/lockup/cancel.t.sol
test/integration/shared/lockup/cancelMultiple.t.sol
test/integration/shared/lockup/streamedAmountOf.t.sol

Addresses the feedback left on https://github.com/sablier-labs/v2-core/pull/656

Address feedback in branching trees

---

README.md

Ref https://github.com/sablier-labs/v2-core/discussions/551

docs: add "Architecture" in README

---

src/interfaces/ISablierV2Lockup.sol
src/interfaces/ISablierV2LockupDynamic.sol
src/interfaces/ISablierV2LockupLinear.sol

Closes https://github.com/sablier-labs/v2-core/issues/611

docs: fix nitpicks

---

src/SablierV2LockupDynamic.sol
src/SablierV2LockupLinear.sol
src/interfaces/ISablierV2LockupDynamic.sol
src/interfaces/ISablierV2LockupLinear.sol
test/fork/LockupDynamic.t.sol
test/fork/LockupLinear.t.sol
test/integration/concrete/lockup-dynamic/get-streams-by-user/getStreamsByUser.t.sol
test/integration/concrete/lockup-dynamic/get-streams-by-user/getStreamsByUser.tree
test/integration/concrete/lockup-linear/get-streams-by-user/getStreamsByUser.t.sol
test/integration/concrete/lockup-linear/get-streams-by-user/getStreamsByUser.tree

Addresses https://github.com/sablier-labs/v2-core/issues/644. @PaulRBerg lmk if you need any changes to the PR. I'll address them myself.

feat: reverse mapping to retrieve stream Ids of a recipient

---

package.json

Closes https://github.com/sablier-labs/v2-core/issues/635.

build: remove oz peer deps

---

CHANGELOG.md
package.json

~~This PR https://github.com/sablier-labs/v2-core/pull/683 is still not merged/closed. We may add the changes here.~~

docs: roll 1.1.0

---

test/Base.t.sol
test/unit/concrete/comptroller/Comptroller.t.sol
test/utils/DeployOptimized.sol
test/utils/Precompiles.t.sol

Closes https://github.com/sablier-labs/v2-core/issues/711

test: add DeployOptimized utils contracts

---

CONTRIBUTING.md

docs: guideline for fork testing

---

.github/workflows/multibuild.yml

See https://github.com/marketplace/actions/foundry-multibuild

ci: foundry multibuild

---

.github/workflows/stale.yml

Experimenting with https://github.com/marketplace/actions/close-stale-issues

ci: bot for closing stale issues and PR

---

script/Init.s.sol
src/SablierV2LockupDynamic.sol
src/SablierV2LockupLinear.sol
src/types/DataTypes.sol
test/fork/LockupDynamic.t.sol
test/fork/LockupLinear.t.sol
test/integration/fuzz/lockup-dynamic/createWithMilestones.t.sol
test/integration/fuzz/lockup-linear/createWithRange.t.sol
test/utils/Defaults.sol

refactor: consistency in calldata related struct parameters

---

src/abstracts/SablierV2Lockup.sol
src/interfaces/ISablierV2Lockup.sol
test/integration/concrete/lockup-dynamic/constructor.t.sol
test/integration/concrete/lockup-linear/constructor.t.sol

Closes https://github.com/sablier-labs/v2-core/issues/763

Make NFT descriptor public

---

script/Base.s.sol
script/DeployCore.s.sol
script/DeployCore2.s.sol
script/DeployCore3.s.sol
script/DeployDeterministicCore.s.sol
script/DeployDeterministicCore2.s.sol
script/DeployDeterministicCore3.s.sol
script/DeployDeterministicLockupDynamic.s.sol
script/DeployLockupDynamic.s.sol
shell/deploy-multi-chain.sh

I have named it `maxCount` because it is going to be used for both segments and tranches.
@PaulRBerg fyi i will update the warp drive

feat: declare maxCount in BaseScript

---

src/SablierV2LockupDynamic.sol
src/SablierV2LockupLinear.sol
src/abstracts/SablierV2Lockup.sol

Ref: https://github.com/crytic/slither/wiki/Printer-documentation#inheritance-graph
This PR updates the count of inherited components.

Update the count of inherited components

---

src/SablierV2LockupDynamic.sol
src/SablierV2LockupTranched.sol
src/libraries/Helpers.sol

Closes https://github.com/sablier-labs/v2-core/issues/847

refactor: rename functions in Helpers

---

test/integration/concrete/lockup-dynamic/constructor.t.sol
test/integration/concrete/lockup-linear/constructor.t.sol
test/integration/concrete/lockup-tranched/constructor.t.sol

As discussed in https://github.com/sablier-labs/v2-core/discussions/854#discussioncomment-8826059.

test for `MAX_BROKER_FEE`

---

src/abstracts/SablierV2Lockup.sol

As discussed in https://github.com/sablier-labs/v2-core/discussions/882.

perf: use unchecked to calculate sender amount

---

test/integration/concrete/lockup-dynamic/LockupDynamic.t.sol
test/integration/concrete/lockup-linear/LockupLinear.t.sol
test/integration/concrete/lockup-tranched/LockupTranched.t.sol
test/integration/concrete/lockup/withdraw-hooks/withdrawHooks.t.sol

Just found out that this was missing too.

test: inherit WithdrawHooks_Integration_Concrete_Test

---

test/fork/NFTDescriptor.t.sol
test/fork/assets/DAI.t.sol
test/fork/assets/EURS.t.sol
test/fork/assets/SHIB.t.sol
test/fork/assets/USDC.t.sol
test/fork/assets/USDT.t.sol

Closes https://github.com/sablier-labs/v2-core/issues/893.
I have also made `NFTDescriptor_Fork_Test` a standalone contract as it doesn't really need forked asset to work.

test: fix NFTDescriptor fork test

---

.github/workflows/ci.yml

Closes https://github.com/sablier-labs/v2-core/issues/897

ci: add `staging-blast` to `ci.yml`

---

foundry.toml
script/Base.s.sol
test/utils/BaseScript.t.sol

Related discussion: https://github.com/sablier-labs/v2-core/discussions/904

build: replace ffi with stdJson for salt creation

---

script/Base.s.sol
shell/update-counts.sh

Closes https://github.com/sablier-labs/v2-core/issues/929

Update count script improvements

---

SECURITY.md

docs: update security assumptions

---

src/abstracts/SablierV2Lockup.sol
test/integration/concrete/lockup/transfer-from/transferFrom.t.sol
test/integration/concrete/lockup/withdraw-max-and-transfer/withdrawMaxAndTransfer.t.sol

Closes https://github.com/sablier-labs/v2-core/issues/939.

perf: emit events before hook calls

---

src/abstracts/SablierV2Lockup.sol
src/interfaces/ISablierV2Lockup.sol
test/integration/concrete/lockup-dynamic/constructor.t.sol
test/integration/concrete/lockup-linear/constructor.t.sol
test/integration/concrete/lockup-tranched/constructor.t.sol

refactor: inherit IERC-4906 in abstract

---

benchmark/Benchmark.t.sol
src/libraries/Errors.sol

Introduces similar changes as those made in https://github.com/sablier-labs/v2-periphery/pull/359#pullrequestreview-2145265541.

test: benchmarks polish

---

CHANGELOG.md
LICENSE.md
package.json
test/utils/BaseScript.t.sol

- Closes https://github.com/sablier-labs/v2-core/issues/861. 
- Closes https://github.com/sablier-labs/v2-core/issues/770.

docs: roll 1.2.0

---

.github/workflows/ci-deep.yml

Closes https://github.com/sablier-labs/v2-core/issues/965
See [Comment](https://github.com/sablier-labs/v2-core/issues/965#issuecomment-2210792700).

ci: replace double quotes with single quotes around input values

---

test/fork/Fork.t.sol
test/fork/LockupDynamic.t.sol
test/fork/LockupLinear.t.sol
test/fork/LockupTranched.t.sol
test/fork/assets/DAI.t.sol
test/fork/assets/EURS.t.sol
test/fork/assets/SHIB.t.sol
test/fork/assets/USDC.t.sol
test/fork/assets/USDT.t.sol

Closes https://github.com/sablier-labs/v2-core/issues/900.
The following name changes were made:
- Rename ASSET to FORK_ASSET
- Rename HOLDER to FORK_ASSET_HOLDER
And all the tests passed:

test(fork): rename `ASSET` to `FORK_ASSET`

---

.github/workflows/ci-deep.yml

@smol-ninja I mean this would work per https://github.com/actions/runner/issues/2424
No fromjson('') can happen like that

fix: ci scheduled run

---

shell/deploy-multi-chain.sh
shell/prepare-artifacts.sh

Please refer to https://github.com/sablier-labs/v2-core/pull/979 notes.
- include periphery in artifacts
- add `core` dir
- add `periphery` dir 
- use deploy protocol deployment script

Update shell scripts to include periphery

---

foundry.toml

Depends on #994 
Closes https://github.com/sablier-labs/v2-core/issues/987

build: remove gas reports field in foundry.toml

---

src/core/interfaces/ISablierLockupDynamic.sol
src/core/interfaces/ISablierLockupLinear.sol
src/core/interfaces/ISablierLockupTranched.sol
src/core/libraries/Errors.sol
src/core/libraries/Helpers.sol
test/core/fork/LockupDynamic.t.sol
test/core/fork/LockupLinear.t.sol
test/core/fork/LockupTranched.t.sol
test/core/integration/concrete/lockup-dynamic/create-with-timestamps/createWithTimestamps.t.sol
test/core/integration/concrete/lockup-dynamic/create-with-timestamps/createWithTimestamps.tree
test/core/integration/concrete/lockup-linear/create-with-timestamps/createWithTimestamps.t.sol
test/core/integration/concrete/lockup-linear/create-with-timestamps/createWithTimestamps.tree
test/core/integration/concrete/lockup-tranched/create-with-timestamps/createWithTimestamps.t.sol
test/core/integration/concrete/lockup-tranched/create-with-timestamps/createWithTimestamps.tree
test/core/integration/fuzz/lockup-dynamic/createWithTimestamps.t.sol
test/core/integration/fuzz/lockup-linear/createWithTimestamps.t.sol
test/core/integration/fuzz/lockup-tranched/createWithTimestamps.t.sol
test/core/integration/shared/lockup/createWithTimestamps.t.sol
test/core/invariant/handlers/LockupLinearCreateHandler.sol
test/utils/Fuzzers.sol
test/utils/Utils.sol

- Closes https://github.com/sablier-labs/v2-core/issues/982

feat: allow end time to be in the past

---

script/DeployCore.s.sol
script/DeployDeterministicCore.s.sol
src/SablierV2LockupDynamic.sol
src/SablierV2LockupLinear.sol
src/SablierV2LockupTranched.sol
src/abstracts/SablierV2Lockup.sol
src/interfaces/ISablierV2LockupDynamic.sol
src/interfaces/ISablierV2LockupLinear.sol
src/interfaces/ISablierV2LockupTranched.sol
src/libraries/Helpers.sol
test/integration/fuzz/lockup-dynamic/createWithDurations.t.sol
test/integration/fuzz/lockup-dynamic/createWithTimestamps.t.sol
test/integration/fuzz/lockup-dynamic/withdraw.t.sol
test/integration/fuzz/lockup-linear/createWithDurations.t.sol
test/integration/fuzz/lockup-linear/createWithTimestamps.t.sol
test/integration/fuzz/lockup-linear/streamedAmountOf.t.sol
test/integration/fuzz/lockup-linear/withdrawableAmountOf.t.sol
test/integration/fuzz/lockup-tranched/createWithDurations.t.sol
test/integration/fuzz/lockup-tranched/createWithTimestamps.t.sol
test/integration/fuzz/lockup-tranched/withdraw.t.sol
test/integration/fuzz/lockup/cancel.t.sol
test/integration/fuzz/lockup/withdraw.t.sol
test/integration/shared/lockup-dynamic/LockupDynamic.t.sol
test/integration/shared/lockup-linear/LockupLinear.t.sol
test/integration/shared/lockup-tranched/LockupTranched.t.sol
test/utils/Fuzzers.sol
test/utils/Utils.sol

Otherwise CI Deep fails on `main` branch. Same as https://github.com/sablier-labs/v2-periphery/pull/384.

style: apply forge formatter

---

src/core/types/DataTypes.sol

Closes https://github.com/sablier-labs/v2-core/issues/975

refactor: amounts type reference in Lockup.Stream struct

---

src/core/SablierLockupDynamic.sol
src/core/SablierLockupLinear.sol
src/core/SablierLockupTranched.sol
src/core/interfaces/ISablierLockupDynamic.sol
src/core/interfaces/ISablierLockupLinear.sol
src/core/interfaces/ISablierLockupTranched.sol
src/core/libraries/Errors.sol
src/core/libraries/Helpers.sol
test/core/integration/concrete/lockup-dynamic/create-with-timestamps/createWithTimestamps.t.sol
test/core/integration/concrete/lockup-dynamic/create-with-timestamps/createWithTimestamps.tree
test/core/integration/concrete/lockup-linear/create-with-timestamps/createWithTimestamps.t.sol
test/core/integration/concrete/lockup-linear/create-with-timestamps/createWithTimestamps.tree
test/core/integration/concrete/lockup-tranched/create-with-timestamps/createWithTimestamps.t.sol
test/core/integration/concrete/lockup-tranched/create-with-timestamps/createWithTimestamps.tree
test/core/integration/fuzz/lockup-dynamic/createWithTimestamps.t.sol
test/core/integration/fuzz/lockup-linear/createWithTimestamps.t.sol
test/core/integration/fuzz/lockup-tranched/createWithTimestamps.t.sol
test/core/integration/shared/lockup/createWithTimestamps.t.sol
test/core/invariant/handlers/BaseHandler.sol

- Closes https://github.com/sablier-labs/v2-core/issues/1008
- Disallow sender to be zero address in all `_create` functions

feat: disallow sender to be zero address

---

script/periphery/CreateMerkleLL.s.sol
src/periphery/SablierMerkleFactory.sol
src/periphery/interfaces/ISablierMerkleFactory.sol
src/periphery/interfaces/ISablierMerkleLL.sol
src/periphery/interfaces/ISablierMerkleLT.sol
src/periphery/types/DataTypes.sol
test/periphery/Periphery.t.sol
test/periphery/fork/merkle-campaign/MerkleLT.t.sol
test/periphery/integration/merkle-campaign/MerkleCampaign.t.sol
test/periphery/integration/merkle-campaign/factory/create-merkle-ll/createMerkleLL.t.sol
test/periphery/integration/merkle-campaign/factory/create-merkle-lt/createMerkleLT.t.sol
test/periphery/integration/merkle-campaign/ll/claim/claim.t.sol
test/periphery/integration/merkle-campaign/ll/claim/claim.tree
test/periphery/integration/merkle-campaign/ll/constructor.t.sol
test/periphery/integration/merkle-campaign/lt/claim/claim.t.sol
test/periphery/integration/merkle-campaign/lt/claim/claim.tree
test/periphery/integration/merkle-campaign/lt/constructor.t.sol
test/utils/Defaults.sol

This PR refactors `claim` tests based on the new changes introduced by https://github.com/sablier-labs/v2-core/pull/1024.

feedback on PR #1024

---

test/core/invariant/handlers/BaseHandler.sol
test/core/invariant/handlers/LockupDynamicCreateHandler.sol
test/core/invariant/handlers/LockupHandler.sol
test/core/invariant/handlers/LockupLinearCreateHandler.sol
test/core/invariant/handlers/LockupTranchedCreateHandler.sol

Closes https://github.com/sablier-labs/v2-core/issues/837.

test: use vm.assume in invariant handlers

---

.github/workflows/ci-deep.yml
.github/workflows/ci-fork.yml

This is what [ChatGPT recommended](https://chatgpt.com/share/66f3f856-20c4-800e-8f9b-65bb7ab23f11).
However, I wanted to double-check the recommendation, so I posted a [Q&A on StackOverflow](https://stackoverflow.com/q/79022703/3873510). Keeping the PR in draft mode until I receive confirmation.

ci: fix slack notify

---

script/GenerateSVG.s.sol
shell/deploy-multi-chain.sh

Hello
I fixed several minor spelling issues.
Hope it helps.

docs fix spelling issues

---

SECURITY.md

Closes https://github.com/sablier-labs/v2-core/issues/1065

docs: adds assumption about permissioned tokens

---

script/periphery/CreateMerkleLL.s.sol
src/periphery/SablierMerkleFactory.sol
src/periphery/SablierMerkleLL.sol
src/periphery/interfaces/ISablierMerkleFactory.sol
src/periphery/interfaces/ISablierMerkleLL.sol
src/periphery/types/DataTypes.sol
test/core/fork/LockupLinear.t.sol
test/periphery/Periphery.t.sol
test/periphery/fork/merkle-campaign/MerkleLL.t.sol
test/periphery/integration/merkle-campaign/MerkleCampaign.t.sol
test/periphery/integration/merkle-campaign/factory/create-merkle-ll/createMerkleLL.t.sol
test/periphery/integration/merkle-campaign/ll/claim/claim.t.sol
test/periphery/integration/merkle-campaign/ll/constructor.t.sol
test/utils/Defaults.sol

As per https://github.com/sablier-labs/v2-core/pull/1075#discussion_r1835522854

refactor: `Schedule` struct

---

script/Init.s.sol
src/SablierBatchLockup.sol
src/SablierLockup.sol
src/libraries/Errors.sol
src/libraries/Helpers.sol
src/types/DataTypes.sol
tests/fork/LockupDynamic.t.sol
tests/fork/LockupLinear.t.sol
tests/fork/LockupTranched.t.sol
tests/integration/concrete/lockup-base/create-with-timestamps/createWithTimestamps.t.sol
tests/integration/concrete/lockup-base/create-with-timestamps/createWithTimestamps.tree
tests/integration/concrete/lockup-dynamic/create-with-timestamps-ld/createWithTimestampsLD.t.sol
tests/integration/concrete/lockup-linear/create-with-timestamps-ll/createWithTimestampsLL.t.sol
tests/integration/concrete/lockup-tranched/create-with-timestamps-lt/createWithTimestampsLT.t.sol
tests/integration/fuzz/lockup-dynamic/createWithTimestampsLD.t.sol
tests/integration/fuzz/lockup-linear/createWithTimestampsLL.t.sol
tests/integration/fuzz/lockup-tranched/createWithTimestampsLT.t.sol
tests/utils/BatchLockupBuilder.sol
tests/utils/Defaults.sol
tests/utils/Modifiers.sol

Polishing https://github.com/sablier-labs/v2-core/pull/1094

refactor: shape param

---

src/libraries/Errors.sol
src/libraries/Helpers.sol
src/libraries/VestingMath.sol

polishing https://github.com/sablier-labs/v2-core/pull/1136

docs: nitpicks

---

CHANGELOG.md

Closes https://github.com/sablier-labs/v2-core/issues/1151

docs: changelog for v2.0.0

---

.github/workflows/ci-fork.yml

Closes https://github.com/sablier-labs/lockup/issues/1172

ci: run fork tests on 2 days a week

---

tests/fork/Fork.t.sol
tests/fork/Lockup.t.sol
tests/fork/LockupDynamic.t.sol
tests/fork/LockupLinear.t.sol
tests/fork/LockupTranched.t.sol
tests/integration/concrete/lockup-base/getters/getters.t.sol
tests/integration/concrete/lockup-dynamic/create-with-durations-ld/createWithDurationsLD.t.sol
tests/integration/concrete/lockup-dynamic/create-with-timestamps-ld/createWithTimestampsLD.t.sol
tests/integration/concrete/lockup-linear/create-with-durations-ll/createWithDurationsLL.t.sol
tests/integration/concrete/lockup-linear/create-with-timestamps-ll/createWithTimestampsLL.t.sol
tests/integration/concrete/lockup-linear/get-unlock-amounts/getUnlockAmounts.t.sol
tests/integration/concrete/lockup-tranched/create-with-durations-lt/createWithDurationsLT.t.sol
tests/integration/concrete/lockup-tranched/create-with-timestamps-lt/createWithTimestampsLT.t.sol
tests/integration/fuzz/lockup-dynamic/createWithDurationsLD.t.sol
tests/integration/fuzz/lockup-dynamic/createWithTimestampsLD.t.sol
tests/integration/fuzz/lockup-linear/createWithDurationsLL.t.sol
tests/integration/fuzz/lockup-linear/createWithTimestampsLL.t.sol
tests/integration/fuzz/lockup-tranched/createWithDurationsLT.t.sol
tests/integration/fuzz/lockup-tranched/createWithTimestampsLT.t.sol
tests/utils/Assertions.sol
tests/utils/Defaults.sol

this PR addresses my feedback on #1179 and includes some additional changes.

avb: tests dry fy

---

.github/workflows/multibuild.yml
foundry.toml

build: bump solc

---

.vscode/extensions.json
.vscode/settings.json
foundry.toml

chore: recommend VSCode extensions

chore: fix taplo

---

src/abstracts/SablierLockupBase.sol
src/interfaces/ISablierLockupBase.sol
src/libraries/Errors.sol
tests/integration/concrete/lockup-base/collect-fees/collectFees.t.sol
tests/integration/concrete/lockup-base/collect-fees/collectFees.tree
tests/invariant/handlers/LockupHandler.sol
tests/utils/Modifiers.sol

This PR is required prior to integrating RBAC and is same as https://github.com/sablier-labs/flow/pull/435. After RBAC is integrated, I will move the common code into the `evm-utils`.
- Closes https://github.com/sablier-labs/lockup/issues/1234
- Closes https://github.com/sablier-labs/lockup/issues/1231

feat: collect fee with fee recipient

---

.solhint.json
bun.lock
package.json
src/SablierLockup.sol
src/abstracts/SablierLockupBase.sol
src/interfaces/ISablierLockupBase.sol
src/libraries/Errors.sol
tests/Base.t.sol
tests/integration/concrete/constructor.t.sol
tests/integration/concrete/lockup-base/collect-fees/collectFees.t.sol
tests/integration/concrete/lockup-base/collect-fees/collectFees.tree
tests/integration/concrete/nft-descriptor/safe-token-symbol/safeTokenSymbol.t.sol
tests/utils/BaseScript.t.sol
tests/utils/DeployOptimized.t.sol
tests/utils/EstimateMaxCount.sol
tests/utils/Modifiers.sol
tests/utils/Types.sol
tests/utils/Utils.sol

- Closes https://github.com/sablier-labs/lockup/issues/1240
- Prefix events with associated interface contract
- Depends on [this discussion](https://github.com/sablier-labs/command-center/discussions/135#discussioncomment-12822384)
- https://github.com/sablier-labs/evm-utils/pull/20

feat: access based control over collect fee function

---

bun.lock
package.json
tests/fork/Fork.t.sol
tests/integration/concrete/lockup-state/burn/burn.t.sol
tests/integration/concrete/lockup-state/cancel/cancel.t.sol
tests/integration/concrete/lockup-state/create-with-timestamps/createWithTimestamps.t.sol
tests/integration/concrete/lockup-state/getters/getters.t.sol
tests/integration/concrete/lockup-state/refundable-amount-of/refundableAmountOf.t.sol
tests/integration/concrete/lockup-state/status-of/statusOf.t.sol
tests/integration/concrete/lockup-state/streamed-amount-of/streamedAmountOf.t.sol
tests/integration/concrete/lockup-state/withdrawable-amount-of/withdrawableAmountOf.t.sol
tests/integration/fuzz/lockup-state/cancel.t.sol
tests/invariant/handlers/BaseHandler.sol
tests/utils/Constants.sol
tests/utils/Defaults.sol

- Closes https://github.com/sablier-labs/lockup/issues/1248
- Partially handles https://github.com/sablier-labs/command-center/issues/146
- Closes https://github.com/sablier-labs/lockup/issues/1227 (don't need immutables anymore)
- Renames bun scripts for linting

build: bump dependencies, refactor Defaults contract

---

src/SablierBatchLockup.sol
src/abstracts/SablierLockupDynamic.sol
src/abstracts/SablierLockupLinear.sol
src/abstracts/SablierLockupTranched.sol
src/interfaces/ISablierBatchLockup.sol
src/types/Lockup.sol
tests/fork/LockupDynamic.t.sol
tests/fork/LockupLinear.t.sol
tests/fork/LockupTranched.t.sol
tests/integration/concrete/batch-lockup/create-with-durations-ld/createWithDurationsLD.t.sol
tests/integration/concrete/batch-lockup/create-with-durations-ld/createWithDurationsLD.tree
tests/integration/concrete/batch-lockup/create-with-durations-ll/createWithDurationsLL.t.sol
tests/integration/concrete/batch-lockup/create-with-durations-ll/createWithDurationsLL.tree
tests/integration/concrete/batch-lockup/create-with-durations-lt/createWithDurationsLT.t.sol
tests/integration/concrete/batch-lockup/create-with-durations-lt/createWithDurationsLT.tree
tests/integration/concrete/batch-lockup/create-with-timestamps-ld/createWithTimestampsLD.t.sol
tests/integration/concrete/batch-lockup/create-with-timestamps-ld/createWithTimestampsLD.tree
tests/integration/concrete/batch-lockup/create-with-timestamps-ll/createWithTimestamps.t.sol
tests/integration/concrete/batch-lockup/create-with-timestamps-ll/createWithTimestamps.tree
tests/integration/concrete/batch-lockup/create-with-timestamps-lt/createWithTimestampsLT.t.sol
tests/integration/concrete/batch-lockup/create-with-timestamps-lt/createWithTimestampsLT.tree
tests/integration/fuzz/lockup-dynamic/createWithTimestampsLD.t.sol
tests/integration/fuzz/lockup-linear/createWithTimestampsLL.t.sol
tests/integration/fuzz/lockup-tranched/createWithTimestampsLT.t.sol
tests/utils/Defaults.sol

Closes https://github.com/sablier-labs/lockup/issues/1273

feat: add `CreateBatch` event in `BatchLockup`

---

scripts/solidity/DeployDeterministicLockupNFTDescriptor.s.sol
scripts/solidity/DeployLockupNFTDescriptor.s.sol

i need this to differentiate between the flow nft descriptor in my deployment CLI script

chore: include "Lockup" in nft descriptor scripts
